// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class MLModel
{
    /// <summary>
    /// model input class for MLModel.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(0)]
        [ColumnName(@"Engine rpm")]
        public float Engine_rpm { get; set; }

        [LoadColumn(1)]
        [ColumnName(@"Lub oil pressure")]
        public float Lub_oil_pressure { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"Fuel pressure")]
        public float Fuel_pressure { get; set; }

        [LoadColumn(3)]
        [ColumnName(@"Coolant pressure")]
        public float Coolant_pressure { get; set; }

        [LoadColumn(4)]
        [ColumnName(@"lub oil temp")]
        public float Lub_oil_temp { get; set; }

        [LoadColumn(5)]
        [ColumnName(@"Coolant temp")]
        public float Coolant_temp { get; set; }

        [LoadColumn(6)]
        [ColumnName(@"Engine Condition")]
        public float Engine_Condition { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for MLModel.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"Engine rpm")]
        public float Engine_rpm { get; set; }

        [ColumnName(@"Lub oil pressure")]
        public float Lub_oil_pressure { get; set; }

        [ColumnName(@"Fuel pressure")]
        public float Fuel_pressure { get; set; }

        [ColumnName(@"Coolant pressure")]
        public float Coolant_pressure { get; set; }

        [ColumnName(@"lub oil temp")]
        public float Lub_oil_temp { get; set; }

        [ColumnName(@"Coolant temp")]
        public float Coolant_temp { get; set; }

        [ColumnName(@"Engine Condition")]
        public float Engine_Condition { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

}
